service: pague-leve-serverless

plugins:
  - serverless-offline
  - serverless-plugin-webpack
  - serverless-aws-documentation

package:
  individually: true

provider:
  name: aws
  timeout: 10
  memorySize: 512
  region: us-east-1
  runtime: nodejs12.x
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: ${self:provider.environment.API_PREFIX}
    blockPublicAccess: true
  environment:
    # Api service
    API_PREFIX: ${self:service}-${self:provider.stage}

    # Sendgrid
    SENDGRID_API_URL: https://api.sendgrid.com/v3
    SENDGRID_API_TOKEN: ${file(./credentials/sendgrid.json):api_token}

    # Data bases
    CUSTOMERS_TABLE: ${self:provider.environment.API_PREFIX}-customers

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["customersTable", "Arn" ] }

custom:
  documentation:
    api:
      info:
        version: "1"
        title: "Sinai simulation API"
        description: "Sinai simulation API for carbon footprint calculations"
        termsOfService: "https://www.sinaitechnologies.com"
        contact:
          name: "João Cardoso"
          url: "https://www.linkedin.com/in/jo%C3%A3o"
          email: "joaoricardo15@hotmail.com"
        license:
          name: "Licensing"
          url: "https://www.sinaitechnologies.com"
    models:
      - name: "ErrorResponse"
        description: "Error payload"
        contentType: "application/json"
        schema: ${file(src/models/error.json)}
      - name: "SuccessResponse"
        description: "Success payload"
        contentType: "application/json"
        schema: ${file(src/models/success.json)}

functions:
  customers-list:
    handler: src/endpoints/customers/list/index.handler
    events:
      - http:
          path: customers
          method: get
          cors: true
          documentation:
            summary: "List customers"
            description: "List all customers"
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "This is how the response body looks like"
                responseModels:
                  "application/json": "SuccessResponse"
              - statusCode: "400"
                responseModels:
                  "application/json": "ErrorResponse"

  customers-post:
    handler: src/endpoints/customers/post/index.handler
    events:
      - http:
          path: customers
          method: post
          cors: true
          documentation:
            summary: "Create customer"
            description: "Create a new customer"
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "This is how the response body looks like"
                responseModels:
                  "application/json": "SuccessResponse"
              - statusCode: "400"
                responseModels:
                  "application/json": "ErrorResponse"
  
  customers-delete:
    handler: src/endpoints/customers/delete/index.handler
    events:
      - http:
          path: customers/{customerId}
          method: delete
          cors: true
          documentation:
            summary: "Delete customer"
            description: "Delete a specified customer by customerId"
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "This is how the response body looks like"
                responseModels:
                  "application/json": "SuccessResponse"
              - statusCode: "400"
                responseModels:
                  "application/json": "ErrorResponse"

  customers-get:
    handler: src/endpoints/customers/get/index.handler
    events:
      - http:
          path: customers/{customerId}
          method: get
          cors: true
          documentation:
            summary: "Get customer"
            description: "Get a specified customer by customerId"
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "This is how the response body looks like"
                responseModels:
                  "application/json": "SuccessResponse"
              - statusCode: "400"
                responseModels:
                  "application/json": "ErrorResponse"

  customers-search:
    handler: src/endpoints/customers/search/index.handler
    events:
      - http:
          path: customers/search/{queryTerm}
          method: get
          cors: true
          documentation:
            summary: "Search customer"
            description: "Search specified customers by text query"
            methodResponses:
              - statusCode: "200"
                responseBody:
                  description: "This is how the response body looks like"
                responseModels:
                  "application/json": "SuccessResponse"
              - statusCode: "400"
                responseModels:
                  "application/json": "ErrorResponse"

resources:
  Resources:
    customersTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.CUSTOMERS_TABLE}
        AttributeDefinitions:
          - AttributeName: customerId
            AttributeType: S
        KeySchema:
          - AttributeName: customerId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
