service: sinai-api

plugins:
  - serverless-offline
  - serverless-plugin-webpack
  - serverless-aws-documentation

package:
  individually: true

provider:
  name: aws
  timeout: 30
  memorySize: 512
  runtime: nodejs12.x
  versionFunctions: false
  environment:
    # Sendgrid
    SENDGRID_API_URL: https://api.sendgrid.com/v3
    SENDGRID_API_TOKEN: ${file(./credentials/sendgrid.json):api_token}

custom:
  documentation:
    api:
      info:
        version: "1"
        title: "Sinai simulation API"
        description: "Sinai simulation API for carbon footprint calculations"
        termsOfService: "https://www.sinaitechnologies.com"
        contact:
          name: "João Cardoso"
          url: "https://www.linkedin.com/in/jo%C3%A3o"
          email: "joaoricardo15@hotmail.com"
        license:
          name: "Licensing"
          url: "https://www.sinaitechnologies.com"
    models:
      -
        name: "ErrorResponse"
        description: "Error message"
        contentType: "application/json"
        schema: ${file(src/models/error.json)}
      -
        name: "SimulationRequest"
        description: "Units: Electricity (kWh/month); Waste (kg/week); Water (litres/day);"
        contentType: "application/json"
        schema: ${file(src/models/simulationRequest.json)}
      -
        name: "SimulationResponse"
        description: "Total carbon emission in kg CO2e/yr"
        contentType: "application/json"
        schema: ${file(src/models/simulationResponse.json)}

functions:
  simulate-footprint:
    handler: src/endpoints/simulateFootprint.handler
    events:
      - http:
          path: simulateFootprint
          method: post
          cors: true
          documentation:
            summary: "Carbon footprint simulation endpoint"
            description: "Takes usage parameters and responses the corresponding carbon emission"
            tags:
              - "Simulate carbon footprint"
            requestBody:
              description: "This is how the request body should looks like."
            requestModels:
              "application/json": "SimulationRequest"
            methodResponses:
              -
                statusCode: "200"
                responseBody:
                  description: "This is how the response body looks like"
                responseModels:
                  "application/json": "SimulationResponse"
              -
                statusCode: "400"
                responseModels:
                  "application/json": "ErrorResponse"
